[package]
name = "woody"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
chrono = "0.4.24"

[dev-dependencies]
tokio = { version = "1", features = ["full", "rt"] }
serial_test = "0.10"
